name: dreamscape
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_gen: ^5.12.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  mason: ^0.1.1
  uikit:
    path: package/uikit
  lottie: ^3.3.2
  
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1
  just_audio: ^0.9.40
  go_router: ^17.0.1
  go_router_builder: ^4.1.3
  drift: ^2.30.0
  path_provider: ^2.1.5
  path: ^1.9.1
  sqlite3_flutter_libs: ^0.5.41
  drift_flutter: ^0.2.8
  flutter_slidable: ^4.0.3
  flutter_popup: ^3.3.9
  supabase_flutter: ^2.12.0
  image_picker: ^1.2.1


dev_dependencies:
  drift_dev: ^2.30.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0
  flutter_flavorizr: ^2.4.1
  flutter_launcher_icons: ^0.14.4

# dependency_overrides:
#   web: ^1.0.0

flutter_gen:
  output: lib/core/gen
  integrations:
    lottie: true
  fonts:
    enabled: true
    outputs:
      class_name: AppFontFamily

workspace:
  - package/uikit

flutter:
  uses-material-design: true
  assets:
    - assets/images/test.png
    - assets/lottie/sleep.json
    - assets/lottie/polar_bear.lottie
    - assets/lottie/Sleeping Polar Bear.json
    - assets/sound/alarm.mp3
    - assets/sound/rain.mp3
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/icomoon.ttf